### ISSUE TITLE
[Enhancement] Disable ping pong with the server

### ISSUE THREAD

**Issue by osfunapps** [OpenXbox/xbox-smartglass-core-node#22]
Hi guys,

I wanted to know if there's a way to ignore the ping from the server (without sending pong), every few seconds, and still maintain the connection.

As the API suggested, there are "packet which needs to be acknowledged".
I was wondering if there is a way to bypass the idea that a connection keeps to be alive by acknowledging these packets.

I tried to ignore the incoming packets but it just caused some weird side effects (connection closed, actions sent to the server got ignored, etc...).

I dunno if this is an option but maybe with the connection request to send "keep connection alive" or something.

Thanks!
Oz.

**Comment by unknownskl** [comment]
Hey!

I've been looking into this and as far i see there is only a ping-pong every 3 seconds. I've tried to delay the response but once that happens, the connection will timeout all the time.
I'm not sure how the client responds, but i believe the behaviour is the same over there.

Is there any reason why you want to reduce the traffic?

**Comment by osfunapps** [comment]
Yap. The client gets disconnected cause the server close the connection, if a pong is delayed.

I want to reduce the times the algorithm packs and unpacks the received packets and the acknowledgments, as the decrypting and encrypting actions are pretty costly.

Do you have an idea on how to predict the packets which need to be acknowledged, without decrypting them? maybe it isn't possible altogether

**Comment by unknownskl** [comment]
I've been checking the timings but it seems to be pretty fast for me. See below:

`smartglass:packet_message Set channel to: 1000000000000000 +3s
smartglass:packet_message Unpacking message: acknowledge +0ms
smartglass:packet_message payload: { low_watermark: 2, processed_list: [], rejected_list: [] } +1ms
smartglass:events Received message. Call: _on_acknowledge() +3s
smartglass:events Packet needs to be acknowledged. Sending response +0ms
smartglass:packet_message [acknowledge] Set: low_watermark = 3 +1ms
smartglass:xbox this._request_num set to 3 +3s
smartglass:packet_message Packing message: acknowledge +1ms
smartglass:events Emit event: _on_acknowledge +2ms
smartglass:client-721 [721] Sending packet to client: 192.168.2.5:5050 +3s

smartglass:packet_message Set channel to: 1000000000000000 +3s
smartglass:packet_message Unpacking message: acknowledge +1ms
smartglass:packet_message payload: { low_watermark: 3, processed_list: [], rejected_list: [] } +0ms
smartglass:events Received message. Call: _on_acknowledge() +3s
smartglass:events Packet needs to be acknowledged. Sending response +1ms
smartglass:packet_message [acknowledge] Set: low_watermark = 4 +1ms
smartglass:xbox this._request_num set to 4 +3s
smartglass:packet_message Packing message: acknowledge +0ms
smartglass:events Emit event: _on_acknowledge +0ms
smartglass:client-721 [721] Sending packet to client: 192.168.2.5:5050 +3s

smartglass:packet_message Set channel to: 1000000000000000 +3s
smartglass:packet_message Unpacking message: acknowledge +1ms
smartglass:packet_message payload: { low_watermark: 4, processed_list: [], rejected_list: [] } +0ms
smartglass:events Received message. Call: _on_acknowledge() +3s
smartglass:events Packet needs to be acknowledged. Sending response +0ms
smartglass:packet_message [acknowledge] Set: low_watermark = 5 +1ms
smartglass:xbox this._request_num set to 5 +3s
smartglass:packet_message Packing message: acknowledge +0ms
smartglass:events Emit event: _on_acknowledge +2ms
smartglass:client-721 [721] Sending packet to client: 192.168.2.5:5050 +3s`

For now i dont see a reason to change the encrypt and decrypt part as it brings more problems then it fixes.
