### ISSUE TITLE
Question: When will events be emitted

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-core-node#24]
Hi, 

I currently try to figure out how I can recognize, that the connection between my client and Xbox has been disconnected. Due to the examples, I should listen to the `_on_console_status`, but it seems like it is never emitted. I am also listening to `_on_timeout` which is also not emitted.

So what is the intended way to recognize a disconnect?

**Comment by unknownskl** [comment]
The `_on_console_status` is emitted when a ConsoleStatus packet has been received. The xbox can send this packet right away after a connection, but can also be send only when the current app changes. There is no reliable way on requesting this information.

The event `_on_timeout` should emitted once the last received packet from the console is more then 15 seconds ago. (See: https://github.com/OpenXbox/xbox-smartglass-core-node/blob/master/src/events.js#L157)

This sample code can be used to catch the timeout:
```this.sgClient.on('_on_timeout', function(connect_client){
    console.log('Timeout detected')
}.bind(this, connect_client))```

**Comment by foxriver76** [comment]
Thanks, I will try it again, but I guess, this is exactly the code I tried. Due to the fact, that I am currently relying on the rest-server, for now, it is enough, to check `sgClient.isConnected` every polling interval. But event-based is, of course, a bit prettier.
