### ISSUE TITLE
ReferenceError: error is not defined

### ISSUE THREAD

**Issue by kaohlive** [OpenXbox/xbox-smartglass-core-node#26]
https://github.com/OpenXbox/xbox-smartglass-core-node/blob/fad2a690f6720ad0bbd5c7a2914d8d88293b0e4c/src/smartglass.js#L188

I am using your awesome module in my project. Once in a while I get this exception that crashes the app. The error states that Error is not defined, and clearly it is not :)

Hope it can be fixed.

Suggest created a new Error object with the description as message and return that.

**Comment by kaohlive** [comment]
My project https://github.com/kaohlive/com.xbox.smartglass

**Comment by unknownskl** [comment]
Nice plugin! I would love to have an Homey myself. 

I will take a look at the bug this weekend and will let you know. Most likely a new version will arrive this weekend (hopefully with this bug fixed).

**Comment by unknownskl** [comment]
The error reporting has been improved. Should be fixed now.

**Comment by kaohlive** [comment]
Looks like a great improvement. Just updated my app to the new version.
