### ISSUE TITLE
Connects during certain XBox states leaves the console in ON mode

### ISSUE THREAD

**Issue by kaohlive** [OpenXbox/xbox-smartglass-core-node#27]
I am sure this is a bad on my side, but in my implementation of your module I poll the console to see if it is on, and try to connect if it is. All works great and fine.
Once in a while the XBox goes into the half on mode during updates. This is detected by my code as on and then I connect. Still all works well but the console behaves like someone started using the console and will not power down any more by itself (since there is a user connected).

So my wish is that I can detect on connect, or before connecting, that the state is this update mode.
Did you test/play with this an can you point me into the right direction?

**Comment by unknownskl** [comment]
This is a good question. I'm not sure if it is possible to detect the update state, but if it is possible, then you could create a flow that if it is going from the 'Update' app to 'Home', to turn off the Xbox. 

I've never encountered this problem, except that I saw my xbox turned on sometimes when I woke up.

**Comment by kaohlive** [comment]
I own five Xbox one's so my change to spot one remaining on is probably a bit larger ;)
I had it again two nights again, but before I got the change to check what app was returned it did turn off again. So I will monitor this behavior and see if it is really a problem or not.

**Comment by unknownskl** [comment]
Hey @kaohlive, i thought about this and what you can do is use the discovery to check if the xbox is on and only connect once it is needed. The xbox will not respond on the discovery packets if it is turned off. Hopefully this will help.
