### ISSUE TITLE
Volume and Mute control

### ISSUE THREAD

**Issue by grzegorz914** [OpenXbox/xbox-smartglass-core-node#28]
Hi,

any possibility to Absolute Volume Control and Mute ON/OFF.

thanks

**Comment by unknownskl** [comment]
Some apps may support the media state using SystemMediaChannel but there is no consistent way of knowing the volume level or if it is muted. Most apps are not supporting the media channel, so it is not really usable.

**Comment by grzegorz914** [comment]
Interesant, 
however I can control volume using hardware buttons in iPhone in RC app (btn.vol_up/btn.vol_down) but can not read the actual volume from console.
