### ISSUE TITLE
volume control doesn't seem to be working

### ISSUE THREAD

**Issue by RUGMJ7443** [OpenXbox/xbox-smartglass-core-node#33]
not sure what im doing wrong but `sgClient.getManager('tv_remote').sendIrCommand('btn.vol_up').then(function(button){ console.log(button) }, function(error){ console.log(error) });
`

doesn't do anything

**Comment by unknownskl** [comment]
What do you get n the logs?

**Comment by unknownskl** [comment]
Closing issue as no further feedback is provided.
