### ISSUE TITLE
Packet Format Not Found

### ISSUE THREAD

**Issue by mariusstrom** [OpenXbox/xbox-smartglass-core-node#34]
Howdy - I'm using xbox-smartglass-core-node as part of a HomeBridge-xbox-tv plugin, and periodically the plugin crashes. The crash tracebook comes from src/packet/packer.js, and the error log shows:

11/8/2020, 7:09:07 PM Error: [packet/packer.js] Packet format not found: 7b226d6163223a2234433a35353a43433a31393a42383a4546222c226273736964223a2237343a41433a42393a34373a32353a4446222c226368616e6e656c223a312c226970223a223139322e3136382e3135372e313634222c2273736964223a227468657374726f6d732e6f7267222c2272737369223a2d34312c2272656d6f74655f7465726d696e616c5f706f7274223a323030302c2274696d65223a313630343839313334373031312c2276657273696f6e223a22454d5745524b2d4a425f315f312d312e342e302e32372c20323032302d30352d32395432333a30363a32385a2c205a656e7472694f532d575a2d332e362e342e30222c2275756964223a2230363431333034313030303030303030343930303232303030463531333733313334333433323333227d
    at loadPacketStructure (/home/hoobs/.hoobs/node_modules/xbox-smartglass-core-node/src/packet/packer.js:22:19)
    at module.exports (/home/hoobs/.hoobs/node_modules/xbox-smartglass-core-node/src/packet/packer.js:35:21)
    at EventEmitter.<anonymous> (/home/hoobs/.hoobs/node_modules/xbox-smartglass-core-node/src/events.js:15:19)
    at EventEmitter.emit (events.js:310:20)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)

Any suggestions? This is on 0.6.5.

**Comment by unknownskl** [comment]
Hi @mariusstrom,

Looks like the packet is received from ZentriOS. Do you something like that running in your network?
The error could be bit less invasive, i will try to push a fix the coming 2 days to change the error to a more verbose log.

**Comment by mariusstrom** [comment]
@unknownskl yeah, I do have a ZentriOS-based device on the network; of all things, I'm pretty sure it's my EV charger.

**Comment by mariusstrom** [comment]
@unknownskl FYI i applied your commit and will update this comment after a bit of burn-in time, hopefully it resolves the failure!

**Comment by mariusstrom** [comment]
@unknownskl looks like this worked! No issues over the entire weekend.

**Comment by unknownskl** [comment]
Thanks for letting know. Published version 0.6.7 which fixes the problem.
